version: "3.9"
services:
  webapi:
    image: containercm.azurecr.io/appproduct/webapi
    build:
      context: ./BackEnd
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - frontend
  frontend:
    image: containercm.azurecr.io/appproduct/frontend
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile
    ports:
        - "4200:80"